# 服务端口
server:
  port: 8202
  # 服务名
spring:
  application:
    name: service-cmn

  # 环境设置：dev、test、prod
  profiles:
    active: dev

  # mysql数据库连接
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yygh_cmn?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

  #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  redis:
    #    host: 192.168.44.165
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0

    #  devtools:
    #    livereload:
    #      port: 88888


    #  spring.redis.lettuce.pool.max-active=20
    #  spring.redis.lettuce.pool.max-wait=-1
    #  #\u6700\u5927\u963B\u585E\u7B49\u5F85\u65F6\u95F4(\u8D1F\u6570\u8868\u793A\u6CA1\u9650\u5236)
    #  spring.redis.lettuce.pool.max-idle=5
    #  spring.redis.lettuce.pool.min-idle=0
    #  mvc:
    #    pathmatch:
    #      matching-strategy: ant_path_matcher


  # nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    #设置sentinel地址
    #    sentinel:
  #      transport:
  #        dashboard=http://127:0:0:1:8858:

  #mongodb地址
  #  data:
  #    mongodb:
  #      host: 192:168:44:163
  #      port: 27017
  #      database: yygh_hosp

  #rabbitmq地址
  #  rabbitmq:
  #    host: 127:0:0:1
  #    port: 5672
  #    username: guest
  #    password: guest

  #配置mapper xml文件的路径
  #mybatis-plus.mapper-locations=classpath:com/atguigu/yygh/mapper/xml/*.xml
  #mybatis-plus:
  #  mapper-locations: classpath:com/shangguigu/shangyitong/mapper/xml/*.xml


  #开启sentinel
  #feign:
  #  sentinel:
  #  enabled: true

  #mongodb地址
  #spring.data.mongodb.host=192.168.44.163
  #spring.data.mongodb.port=27017
  #spring.data.mongodb.database=yygh_hosp

  #rabbitmq地址
#spring.rabbitmq.host=127.0.0.1
#spring.rabbitmq.port=5672
#spring.rabbitmq.username=guest
#spring.rabbitmq.password=guest

#分为：OFF、FATAL、ERROR、WARN、INFO、DEBUG、ALL
#logging:
#  level:
#    root: debug
